### ISSUE TITLE
Is this active?

### ISSUE THREAD

**Issue by Aaronov** [baryshev/ect#101]
Is ECT in active development or has it been abandoned? Been 2 years since a commit...

**Comment by baryshev** [comment]
You can checkout [next](https://github.com/baryshev/ect/tree/next) branch, also it available in npm as `ect@1.0.0`. I know that many things need to be improved, and i'm trying to make it possible, but i need more free time to do it.

**Comment by baryshev** [comment]
Also, I'm using ect in all my node.js based web projects, and feel comfortable. It still very fast and i think the template syntax is good enough.

**Comment by Aaronov** [comment]
Thanks for letting me know! I am looking for best performing engine and I already use ECT but wanted to re-evaluate for a new project if ECT wasn't being maintained. I'll look at 1.0.0.
