### ISSUE TITLE
Можно ли обратиться напрямую к контексту (данным) шаблона

### ISSUE THREAD

**Issue by disfated** [baryshev/ect#19]
Приведу пример

```
<% include 'partials/showcase', [ '001', '002', '003' ] %>
```

partials/showcase.ect:

```
<% for image in @context : %>
    <a href="/img/<% image %>.jpg"><img src="/img/<% image %>_tn.jpg" /></a>
<% end %>
```

Думаю, кейс понятен. Вопрос в том как обратиться напрямую к переданному контексту. Понятно, что можно передавать `{ items: [ ... ] }`, а потом получать с помощью `for image in @items`, но не очень красиво.

**Comment by baryshev** [comment]
Да, `@` является ссылкой на контекст.

``` js
<% for image in @ : %>
    <a href="/img/<%- image %>.jpg"><img src="/img/<%- image %>_tn.jpg" /></a>
<% end %>
```

**Comment by disfated** [comment]
Ещё `this` работает...
А может это в документации отразить?

**Comment by disfated** [comment]
Кстати, есть ли способ программно строки отправлять в выдачу? Типа `echo`.

```
for image in @
    echo '<a href="/img' + image + '">bla</a>'
```

Что-то типа этого

**Comment by baryshev** [comment]
Через функцию например. Но это не очень хороший стиль для шаблонов.

``` js
<% showImages = (images) ->
  html = ''
  for image in images
    html += '<img src="' + image + '.jpg" />'
  html
%>

<%- showImages([7,4,5,6,7]) %>
```

**Comment by disfated** [comment]
Точно :)
Извиняюсь за беспокойство, осознал, что все вопросы от незнания кофе-скрипта.
