### ISSUE TITLE
coffee-script version

### ISSUE THREAD

**Issue by yuri-karadzhov** [baryshev/ect#27]
Can you change package.json, so coffee-script depends on the latest coffee-script

```
coffee-script: ">=1.5.0"
```

because after require ect

```
ect = require 'ect'
```

coffee interpreter acts like 1.5.0 and does not work with my scripts because they made for version 1.6.2 (some sugar with brackets)

**Comment by baryshev** [comment]
Done.

**Comment by yuri-karadzhov** [comment]
thanks a lot!!!
