### ISSUE TITLE
Comments in ECT.

### ISSUE THREAD

**Issue by ghost** [baryshev/ect#31]
Vadim,

I there a way to leave a comment in a .ect file? I cant find any documentation about that.

Example:

```
<% /* my comment */ %>
or
<% // my comment %>
```

**Comment by baryshev** [comment]
You can use html-comments outside of ECT control tags.

``` html
<!-- my comment -->
```

If you need to leave a comment inside of multiline ECT expression, you can use coffee-script comments:

```
<%
@test = 1
# @test = 2 just a comment
%>
<%- @test %>
```
