### ISSUE TITLE
Express app.locals variables not accessible from in ECT template

### ISSUE THREAD

**Issue by babsonmatt** [baryshev/ect#34]
Can anyone else confirm this?

app.locals({
    name: 'joe'
})

<%- name %>

This should render 'joe', however it says 'name is undefined'.

I tried Swig as an alternative, and Swig appears to work fine.

**Comment by baryshev** [comment]
You trying to access local variable `name`. All input variables need to be prefixed with `@` (this).
Try to output with this code:

`<%- @name %>`

**Comment by juanmaia** [comment]
Is anyone looking at this?
