### ISSUE TITLE
Demo is broken on the site.

### ISSUE THREAD

**Issue by jeromegn** [baryshev/ect#38]
I want to convey how awesome this is. Difficult without a demo! :)

**Comment by baryshev** [comment]
Working for me in Chrome, FF and Opera. Demo can be broken with old IE or another browsers without ACE editor support. ECT working in all major browsers (IE >= 7.0).

**Comment by jeromegn** [comment]
I get "Uncaught ReferenceError: hljs is not defined " on the latest stable Chrome.

Does work in Safari.

**Comment by baryshev** [comment]
Looks like this file not loaded for you http://yandex.st/highlightjs/7.2/highlight.min.js

**Comment by baryshev** [comment]
I moved it into my server. You can try again now, it should work.
