### ISSUE TITLE
Escaped text with breaks

### ISSUE THREAD

**Issue by ghost** [baryshev/ect#44]
Is there simple "ECT" way to escape the user entered text and add breaks?

I use MongoDB witch has JSON data and it has \n witch i want to translate to breaks.

`<%= @company.description.replace(/\n/g, '<br>') %>`

This code will escape `<br>` tags also.

**Comment by baryshev** [comment]
You can use power of CoffeeScript:

data:

```
{
  company : companyFromMongo,
  breakHelper : function (str) { return str.replace(/\n/g, '<br>'); }
}
```

template:

```
<%= @breakHelper @company.description %>
<%= @breakHelper @company.contacts %>
<%= @breakHelper @company.people %>
```
