### ISSUE TITLE
Обработка расширения файла

### ISSUE THREAD

**Issue by sega-yarkin** [baryshev/ect#47]
В директории с шаблонами есть файл `select.ect`, используя пример из документации

``` javascript
var ECT = require('ect');
var renderer = ECT({ root : __dirname + '/views', ext : '.ect' });
renderer.render('select', {}, function (error, html) {
    ...
});
```

получаем ошибку, что не найден `se.ect`. :-)
Поправьте, пожалуйста, создание регулярки в функции `TemplateContext.prototype.load` хотя бы на что-нибудь типа:

``` javsscript
var extExp = new RegExp(ect.options.ext.replace('.','\\.') + '$');
```

Спасибо!

**Comment by baryshev** [comment]
Залил в npm, версия 0.5.5.
