### ISSUE TITLE
Add support for async code.

### ISSUE THREAD

**Issue by dmitry-solomadin** [baryshev/ect#5]
In our app in some very rare cases there is need to directly access db from templates, this could only be done via async query and it would be nice if ECT could support it. i.e such code

``` coffeescript
<% do @getCount (countFromDB) -> : %>
  <span>The count is <%= countFromDB %></span>
<% end %>
```

**Comment by dmitry-solomadin** [comment]
http://www.slideshare.net/kainosnoema/ajs-asynchronous-templating-in-node

Slides 39-43 contain some info on how this is implemented in AJS.

**Comment by baryshev** [comment]
No plans now to support async code in templates, sorry. ECT is performance focused engine, but async code support need to implement some additional functionality that impacts performance.
