### ISSUE TITLE
Take out cache property or create little API to manipulate cache

### ISSUE THREAD

**Issue by darky** [baryshev/ect#51]

**Comment by baryshev** [comment]
`clearCache` method added in v.0.5.6.

**Comment by darky** [comment]
Не совсем правильно. Метод `clearCache` довольно частный случай. 
Лучше удалить `clearCache` и просто вынести приватное свойство `cache` наружу `this.cache = cache` . Или сразу объявить открытым объектом и учесть это везде в коде. Тогда у разработчика развяжутся руки и он напишет свои методы `clearCache`, `appendToCache`, `findInCache`, `sendCacheToMoon`, что угодно.

```

Would be better take out cache property. Then developer feel free to write own cache API
```
