### ISSUE TITLE
Error: callback function required

### ISSUE THREAD

**Issue by lukszy** [baryshev/ect#53]
Hi, 
i keep getting this error when trying to setup etc with express 

Error: callback function required 

on 

app.engine('.ect', ectRenderer.render);

Node v 0.10.24 Express v 3.4.7

**Comment by baryshev** [comment]
I tried and have no problems with lastest versions of node.js, ect and express.
You can try to download and check [working example](https://googledrive.com/host/0B6HRfD7im2zIYlNUcmFpWnZBV3M/ecttest.zip).
