### ISSUE TITLE
Add support for capture blocks on functions

### ISSUE THREAD

**Issue by sebmck** [baryshev/ect#7]
The following code errors:

``` coffeescript
ect = require 'ect'
fs  = require 'fs'

ect = ect {}

fs.writeFileSync 'test.ect', '<%- @test do => %>foo<% end %>'

console.log ect.render 'test.ect', test: (str) ->
    "#{str}bar"

fs.unlinkSync 'test.ect'
```

The expected result should be 'foobar' instead it errors with the following message `SyntaxError: missing ) in test.ect`.

Works fine on eco and is the only thing stopping me from using this library as a large majority of our views do this to pass HTML to view helpers.

Great library, thanks!

**Comment by baryshev** [comment]
Thanks for report. Will be fixed soon. (Estimated time: 1 week)

**Comment by baryshev** [comment]
Added in version 0.4.1
