### ISSUE TITLE
Bower install should include unminified ect.js

### ISSUE THREAD

**Issue by TrevorBurnham** [baryshev/ect#72]
Currently, running "bower install ect" only gives you `ect.min.js` and `ect.min.map`, with `ect.min.js` specified as `main`. This violates the [bower.json spec](https://github.com/bower/bower.json-spec#main), which specifies for the `main` field:

> Do not include minified files.

**Comment by baryshev** [comment]
Fixed. Thanks!

**Comment by TrevorBurnham** [comment]
Great, thanks for fixing!
