### ISSUE TITLE
"locals" variable is not availible in express render

### ISSUE THREAD

**Issue by tiberule** [baryshev/ect#8]
"locals" is the default variable passed to render engine by express app. after few hours or researching, I've found it's possible to access part of "locals" data in "_locals" variable. 

here is the example:
//setting locals data
app.use(function(req, res, next){
    res.locals.messages = req.flash();
    res.locals.user = req.user;
    console.dir(res.locals);
    next();
});
//accessing it
    <% if @_locals and @_locals['messages'] : %>
      <% if @_locals.messages['error'] : %>
      <div class="alert alert-error">
        <%- @_locals.messages['error'] %>
      </div>
      <% end %>
    <% end %>

**Comment by baryshev** [comment]
You don't need to use any prefix (_locals or locals) in template to access `locals`. In your case you can simple access error with this code:

``` js
<%- @messages.error %>
```

You don't need additional check error variable existence. ECT just output empty string if `messages.error` not defined. But if you need to access any sub object (error.message for example) you can use CoffeeScript existential operator:

``` js
<%- @messages.error?.message %>
```

This code outputs `locals.messages.error.message` if exists and empty string if locals.messages.error is undefined.
